-- Profile archive for Himalayas talent crawl + outreach status.
-- Safe to run more than once. Existing live tables keep their columns; ALTERs add outreach fields.

create table if not exists public.talent_profiles (
  id bigint generated by default as identity primary key,
  talent_slug text not null unique,
  candidate_name text not null default '',
  profile_url text not null default '',
  category text not null default '',
  stack jsonb not null default '[]'::jsonb,
  country text not null default '',
  status text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Optional profile text (some crawls store it; drafting works without it).
alter table public.talent_profiles add column if not exists summary text not null default '';

-- Outreach status / multi-bot coordination (run once on an existing table).
-- status: '' pending | queued | sent | skip | failed
alter table public.talent_profiles add column if not exists status text not null default '';
alter table public.talent_profiles add column if not exists error text;
alter table public.talent_profiles add column if not exists account_id text;
alter table public.talent_profiles add column if not exists account_label text;
alter table public.talent_profiles add column if not exists message_body text not null default '';
alter table public.talent_profiles add column if not exists sent_at timestamptz;

create index if not exists talent_profiles_country_idx on public.talent_profiles (country);
create index if not exists talent_profiles_category_idx on public.talent_profiles (category);
create index if not exists talent_profiles_updated_idx on public.talent_profiles (updated_at desc);
create index if not exists talent_profiles_status_idx on public.talent_profiles (status);
create index if not exists talent_profiles_account_idx on public.talent_profiles (account_id);

alter table public.talent_profiles enable row level security;

drop policy if exists "service can manage talent profiles" on public.talent_profiles;
create policy "service can manage talent profiles"
on public.talent_profiles
for all
to anon
using (true)
with check (true);

-- Optional: wipe and start empty (uncomment only if you want a full reset of this archive)
-- truncate table public.talent_profiles restart identity;
