create table if not exists public.outreach_contacts (
  id bigint generated by default as identity primary key,
  talent_slug text not null unique,
  candidate_name text not null,
  profile_url text not null default '',
  summary text not null default '',
  category text not null default 'unknown',
  stack jsonb not null default '[]'::jsonb,
  message_id bigint,
  message_body text not null default '',
  sent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.outreach_contacts enable row level security;

drop policy if exists "service can manage outreach contacts" on public.outreach_contacts;
create policy "service can manage outreach contacts"
on public.outreach_contacts
for all
to anon
using (true)
with check (true);

-- Outreach status (run once, safe to run again).
-- Each member has one row. status is "queued" (one profile has claimed the member and will send),
-- "sent", or "failed". Both "queued" and "sent" block every other profile from a first message.
-- Only the profile that wrote the "queued" row may still deliver that message.
-- Existing rows are all sent, so they become "sent".
alter table public.outreach_contacts add column if not exists status text not null default 'sent';
alter table public.outreach_contacts add column if not exists error text;
alter table public.outreach_contacts add column if not exists account_id text;
alter table public.outreach_contacts add column if not exists account_label text;
alter table public.outreach_contacts add column if not exists updated_at timestamptz not null default now();
alter table public.outreach_contacts add column if not exists country text not null default '';
-- Queued and failed rows have no send time yet.
alter table public.outreach_contacts alter column sent_at drop not null;
alter table public.outreach_contacts alter column sent_at drop default;
create index if not exists outreach_contacts_status_idx on public.outreach_contacts (status);
create index if not exists outreach_contacts_account_idx on public.outreach_contacts (account_id);

-- Nothing else is needed: the "service can manage outreach contacts" policy above already lets the app
-- read, insert, and update rows, which is what status changes use.
